In [1]:
!pip install ipython-autotime > /dev/null
%load_ext autotime

time: 2.17 ms (started: 2021-09-10 14:54:44 +00:00)


# [A Stack-Propagation Framework with Token-Level Intent Detection for Spoken Language Understanding](https://github.com/LeePleased/StackPropagation-SLU)

In [ ]:
# !git clone https://github.com/amiralikaboli/StackPropagation-SLU.git drive/MyDrive/Dev/ID_in_CRS/StackPropagation-SLU > /dev/null

In [ ]:
!pip install ordered_set > /dev/null
!cd drive/MyDrive/Dev/ID_in_CRS/StackPropagation-SLU && python train.py -dd ../../../Datasets/MultiWOZ_2.2_v2 -ne 20 -bs 32 -wed 100

Training parameters are listed as follows:

	number of train sample:                    49023;
	number of dev sample:                      6367;
	number of test sample:                     6338;
	number of epoch:						    20;
	batch size:							    32;
	learning rate:							    0.001;
	random seed:							    0;
	rate of l2 penalty:					    1e-06;
	rate of dropout in network:                0.4;
	teacher forcing rate(slot)		    		0.9;
	teacher forcing rate(intent):		    	0.9;

End of parameters show. Save dir: save.


/usr/local/lib/python3.7/dist-packages/torch/nn/modules/rnn.py:65: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.4 and num_layers=1
  "num_layers={}".format(dropout, num_layers))
Model parameters are listed as follows:

	number of word:                            3073;
	number of slot:                            60;
	number of intent:						    11;
	word embedding dimensi

# [A Co-Interactive Transformer for Joint Slot Filling and Intent Detection](https://github.com/kangbrilliant/DCA-Net)

In [1]:
# !git clone https://github.com/amiralikaboli/DCA-Net.git drive/MyDrive/Dev/ID_in_CRS/CoInteractive-Transformer > /dev/null

fatal: destination path 'drive/MyDrive/Dev/ID_in_CRS/CoInteractive-Transformer' already exists and is not an empty directory.


In [ ]:
# !mkdir -p ~/.kaggle
# !cp drive/MyDrive/kaggle.json ~/.kaggle/
# !chmod 600 ~/.kaggle/kaggle.json
# !kaggle datasets download thanakomsn/glove6b300dtxt > /dev/null
# !unzip glove6b300dtxt.zip -d drive/MyDrive/Dev/ID_in_CRS/CoInteractive-Transformer/data > /dev/null

In [3]:
import json

src_path = "drive/MyDrive/Datasets/MultiWOZ_2.2_v2"
dst_path = "drive/MyDrive/Dev/ID_in_CRS/CoInteractive-Transformer/data"

intent_label = "intents"
slot_label = "slots1"


vocab = ["<pad>", "<unk>", "</s>", "</e>"]
with open(f"{src_path}/words.json", "r") as json_file:
    vocab.extend(json.load(json_file))
with open(f"{dst_path}/vocab.txt", "w") as txt_file:
    txt_file.writelines([f"{word}\n" for word in vocab])

intents = ["general"]
with open(f"{src_path}/{intent_label}.json", "r") as json_file:
    intents.extend(json.load(json_file))
with open(f"{dst_path}/intent_label.txt", "w") as txt_file:
    txt_file.writelines([f"{idx}\t{intent}\n" for idx, intent in enumerate(intents)])

slots = ["<PAD>", "<start>", "<end>"]
with open(f"{src_path}/{slot_label}.json", "r") as json_file:
    slots.extend(json.load(json_file))
with open(f"{dst_path}/slot_label.txt", "w") as txt_file:
    txt_file.writelines([f"{idx}\t{slot}\n" for idx, slot in enumerate(slots)])

In [5]:
!cd drive/MyDrive/Dev/ID_in_CRS/CoInteractive-Transformer && python main_joint.py

Epoch:   0% 0/20 [00:00<?, ?it/s][0.001]
100% 1532/1532 [02:37<00:00,  9.73it/s]
100% 199/199 [00:19<00:00, 10.20it/s]
              precision    recall  f1-score   support

           0     0.8790    0.9786    0.9261      1166
           1     0.9402    0.6962    0.8000       339
           2     0.8327    0.6869    0.7528       297
           3     0.7487    0.8109    0.7785       349
           4     0.8211    0.7123    0.7629       883
           6     0.1000    0.5000    0.1667         2
           7     0.9145    0.7409    0.8186       938
           9     0.6198    0.8503    0.7170       882
          10     0.9561    0.5976    0.7355       328
          11     0.8770    0.9222    0.8991      1183

    accuracy                         0.8208      6367
   macro avg     0.7689    0.7496    0.7357      6367
weighted avg     0.8376    0.8208    0.8207      6367


Evaluation - intent_loss: 0.543633 slot_loss: 1.239405 acc: 0.8208% slot f1: 0.7823 sent acc: 0.6485 

Epoch:   5% 1/20 [

# [A Bi-model based RNN Semantic Frame Parsing Model for Intent Detection and Slot Filling](https://github.com/ray075hl/Bi-Model-Intent-And-Slot)

In [ ]:
# !git clone https://github.com/amiralikaboli/Bi-Model-Intent-And-Slot.git drive/MyDrive/Dev/ID_in_CRS/Bi-Model-Intent-And-Slot  > /dev/null

In [ ]:
!cd drive/MyDrive/Dev/ID_in_CRS/Bi-Model-Intent-And-Slot && python train_args.py -te 20 -bb 32 -es 50 -lhs 192

Number of training samples:  48779
Number of test samples:  6298
Number of words:  1959
Number of intent labels:  11
Number of slot labels 60
##################################################
{'book_hotel': 0, 'book_restaurant': 1, 'book_train': 2, 'find_attraction': 3, 'find_hospital': 4, 'find_hotel': 5, 'find_police': 6, 'find_restaurant': 7, 'find_taxi': 8, 'find_train': 9, 'general': 10}
1524it [10:48,  2.35it/s]
196it [00:28,  6.93it/s]
Epoch: [1/20], Intent Val Acc: 84.71 	 Slot F1 score: 83.81
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no tru

# Hyperparameters Tunning

In [ ]:
import random

results = []
for _ in range(10):
    ne = 7
    bs = random.choice([16])
    wed = random.choice([100])
    ehd = random.choice([192, 256])
    lr = random.uniform(1e-4, 1e-2)

    print(bs, wed, ehd)

    !cd drive/MyDrive/Development/ID_in_CRS/Bi-Model-Intent-And-Slot && python train_args.py -te {ne} -bb {bs} -es {wed} -lhs {ehd}

    print("#" * 30)

# Fasttext

In [2]:
!pip install fasttext > /dev/null

time: 47.7 s (started: 2021-09-10 14:54:44 +00:00)


In [26]:
import json
import numpy as np
import fasttext
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix

time: 3.88 ms (started: 2021-09-10 15:07:07 +00:00)


In [4]:
data_path = "drive/MyDrive/Datasets/MultiWOZ_2.2_v2"

time: 1.22 ms (started: 2021-09-10 14:55:32 +00:00)


In [30]:
with open(f"{data_path}/train.json", "r") as json_file:
    train_data = json.load(json_file)
with open(f"{data_path}/validation.json", "r") as json_file:
    val_data = json.load(json_file)
with open(f"{data_path}/test.json", "r") as json_file:
    test_data = json.load(json_file)

time: 1.05 s (started: 2021-09-10 15:07:49 +00:00)


In [31]:
intent_label = "intents"

def read_data(data):
    X, y = [], []

    for id, dlg in data.items():
        for trn in dlg:
            if trn["speaker"] == 1:
                continue

            if len(trn[intent_label]) > 1:
                continue

            X.append(" ".join(trn["words"]))
            if len(trn[intent_label]) == 1:
                y.append(trn[intent_label][0])
            else:
                y.append("general")

    return X, y

X_train, y_train = read_data(train_data)
X_val, y_val = read_data(val_data)
X_test, y_test = read_data(test_data)

time: 105 ms (started: 2021-09-10 15:08:33 +00:00)


In [32]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_val = encoder.transform(y_val)
y_test = encoder.transform(y_test)

{class_name: idx for idx, class_name in enumerate(encoder.classes_)}

{'book_hotel': 0,
 'book_restaurant': 1,
 'book_train': 2,
 'find_attraction': 3,
 'find_hospital': 4,
 'find_hotel': 5,
 'find_police': 6,
 'find_restaurant': 7,
 'find_taxi': 8,
 'find_train': 9,
 'general': 10}

time: 45.3 ms (started: 2021-09-10 15:08:34 +00:00)


In [33]:
def prepare_fasttext_file(filename, X, Y):
    with open(f"{filename}.txt", "w") as txt_file:
        for x, y in zip(X, Y):
            txt_file.write(f"__label__{y} {x}\n")

prepare_fasttext_file("train", X_train, y_train)
prepare_fasttext_file("val", X_val, y_val)
prepare_fasttext_file("test", X_test, y_test)

time: 66.5 ms (started: 2021-09-10 15:08:39 +00:00)


In [16]:
import gc

del train_data, X_train, y_train
del val_data, X_val, y_val
del test_data

gc.collect()

88

time: 127 ms (started: 2021-09-10 14:57:48 +00:00)


In [38]:
model = fasttext.train_supervised(
    input="train.txt",
    autotuneValidationFile="val.txt",
    epoch=3
)

time: 5min 11s (started: 2021-09-10 15:10:24 +00:00)


In [39]:
preds, _ = model.predict(X_test)
preds = np.array([int(pred_label[0][-1]) for pred_label in preds])
print(classification_report(y_test, preds, digits=4))
print(confusion_matrix(y_test, preds))

              precision    recall  f1-score   support

           0     0.1776    0.7902    0.2901       348
           1     0.8548    0.7235    0.7837       293
           2     0.8204    0.7423    0.7794       357
           3     0.8619    0.8468    0.8543       914
           4     0.0000    0.0000    0.0000         0
           5     0.8396    0.8512    0.8454       941
           6     0.5000    0.5000    0.5000         2
           7     0.8163    0.7981    0.8071       852
           8     0.9512    0.8357    0.8897       280
           9     0.9136    0.9455    0.9293      1230
          10     0.0000    0.0000    0.0000      1121

    accuracy                         0.6950      6338
   macro avg     0.6123    0.6394    0.6072      6338
weighted avg     0.6737    0.6950    0.6731      6338

[[ 275    8   12    5    0   35    0    7    1    5    0]
 [  27  212   12    2    0    3    0   31    1    5    0]
 [  23    6  265    2    0    1    0    0    0   60    0]
 [  29    0  

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
