In [ ]:
!pip install ipython-autotime > /dev/null
%load_ext autotime

time: 224 µs (started: 2021-08-27 13:58:52 +00:00)


# [A Stack-Propagation Framework with Token-Level Intent Detection for Spoken Language Understanding](https://github.com/LeePleased/StackPropagation-SLU)

In [ ]:
# !git clone https://github.com/LeePleased/StackPropagation-SLU drive/MyDrive/Dev/ID_in_CRS/StackPropagation-SLU > /dev/null
# !rm -rf drive/MyDrive/Dev/ID_in_CRS/StackPropagation-SLU/data

In [ ]:
!pip install ordered_set > /dev/null

In [ ]:
import random

results = []
for _ in range(10):
    ne = 10
    bs = random.choice([16, 32, 64])
    wed = random.choice([30, 50, 100])
    ehd = random.choice([64, 128, 256])

    print(ne, bs, wed, ehd)

    !cd drive/MyDrive/Dev/ID_in_CRS/StackPropagation-SLU && python train.py -dd ../../../Datasets/MultiWOZ_2.2 -ne {ne} -bs {bs} -wed {wed} -ehd {ehd}

    print("#" * 100)

In [ ]:
!pip install ordered_set > /dev/null
!cd drive/MyDrive/Dev/ID_in_CRS/StackPropagation-SLU && python train.py -dd ../../../Datasets/MultiWOZ_2.2 -bs 64 -wed 100

Training parameters are listed as follows:

	number of train sample:                    38810;
	number of dev sample:                      5100;
	number of test sample:                     5117;
	number of epoch:						    300;
	batch size:							    64;
	learning rate:							    0.001;
	random seed:							    0;
	rate of l2 penalty:					    1e-06;
	rate of dropout in network:                0.4;
	teacher forcing rate(slot)		    		0.9;
	teacher forcing rate(intent):		    	0.9;

End of parameters show. Save dir: save.


/usr/local/lib/python3.7/dist-packages/torch/nn/modules/rnn.py:65: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.4 and num_layers=1
  "num_layers={}".format(dropout, num_layers))
Model parameters are listed as follows:

	number of word:                            2315;
	number of slot:                            59;
	number of intent:						    8;
	word embedding dimensi

# [A Co-Interactive Transformer for Joint Slot Filling and Intent Detection](https://github.com/kangbrilliant/DCA-Net)

In [ ]:
# !git clone https://github.com/kangbrilliant/DCA-Net.git drive/MyDrive/Dev/ID_in_CRS/CoInteractive-Transformer > /dev/null
# !rm -rf drive/MyDrive/Dev/ID_in_CRS/CoInteractive-Transformer/data/*
# !rm -rf drive/MyDrive/Dev/ID_in_CRS/CoInteractive-Transformer/ckpt/*

In [ ]:
# !mkdir -p ~/.kaggle
# !cp drive/MyDrive/kaggle.json ~/.kaggle/
# !chmod 600 ~/.kaggle/kaggle.json
# !kaggle datasets download thanakomsn/glove6b300dtxt > /dev/null
# !unzip glove6b300dtxt.zip -d drive/MyDrive/Dev/ID_in_CRS/CoInteractive-Transformer/data > /dev/null

In [ ]:
# import json

# src_path = "drive/MyDrive/Datasets/MultiWOZ_2.2"
# dst_path = "drive/MyDrive/Dev/ID_in_CRS/CoInteractive-Transformer/data"

# intent_label = "intents"
# slot_label = "slots1"


# vocab = ["<pad>", "<unk>", "</s>", "</e>"]
# with open(f"{src_path}/words.json", "r") as json_file:
#     vocab.extend(json.load(json_file))
# with open(f"{dst_path}/vocab.txt", "w") as txt_file:
#     txt_file.writelines([f"{word}\n" for word in vocab])

# intents = ["general"]
# with open(f"{src_path}/{intent_label}.json", "r") as json_file:
#     intents.extend(json.load(json_file))
# with open(f"{dst_path}/intent_label.txt", "w") as txt_file:
#     txt_file.writelines([f"{idx}\t{intent}\n" for idx, intent in enumerate(intents)])

# slots = ["<PAD>", "<start>", "<end>"]
# with open(f"{src_path}/{slot_label}.json", "r") as json_file:
#     slots.extend(json.load(json_file))
# with open(f"{dst_path}/slot_label.txt", "w") as txt_file:
#     txt_file.writelines([f"{idx}\t{slot}\n" for idx, slot in enumerate(slots)])

In [ ]:
!cd drive/MyDrive/Dev/ID_in_CRS/CoInteractive-Transformer && python main_joint.py

Epoch:   0% 0/20 [00:00<?, ?it/s][0.001]
100% 1213/1213 [01:02<00:00, 19.36it/s]
100% 160/160 [00:08<00:00, 19.97it/s]
              precision    recall  f1-score   support

           1     0.8416    0.6115    0.7083       278
           2     0.6272    0.9203    0.7460       903
           3     0.8006    0.6327    0.7068       863
           4     0.9010    0.7182    0.7993       912
           5     0.8691    0.8951    0.8819      1172
           6     0.6675    0.8275    0.7389       342
           7     0.8391    0.7065    0.7671       310
           8     0.8787    0.7469    0.8074       320

    accuracy                         0.7827      5100
   macro avg     0.8031    0.7573    0.7695      5100
weighted avg     0.8041    0.7827    0.7827      5100


Evaluation - intent_loss: 0.610308 slot_loss: 1.634842 acc: 0.7827% slot f1: 0.7749 sent acc: 0.5806 

Epoch:   5% 1/20 [01:12<22:49, 72.06s/it][0.001]
100% 1213/1213 [01:01<00:00, 19.82it/s]
100% 160/160 [00:07<00:00, 20.21it/s]

# [A Bi-model based RNN Semantic Frame Parsing Model for Intent Detection and Slot Filling](https://github.com/ray075hl/Bi-Model-Intent-And-Slot)

In [ ]:
# !git clone https://github.com/ray075hl/Bi-Model-Intent-And-Slot.git drive/MyDrive/Dev/ID_in_CRS/Bi-Model-Intent-And-Slot  > /dev/null
# !rm -rf drive/MyDrive/Dev/ID_in_CRS/Bi-Model-Intent-And-Slot/data*

In [ ]:
!cd drive/MyDrive/Dev/ID_in_CRS/Bi-Model-Intent-And-Slot && python train_args.py -te 10 -bb 32 -es 50 -lhs 192

Number of training samples:  39865
Number of test samples:  5235
Number of words:  2407
Number of intent labels:  10
Number of slot labels 18
##################################################
{'book_hotel': 0, 'book_restaurant': 1, 'book_train': 2, 'find_attraction': 3, 'find_hospital': 4, 'find_hotel': 5, 'find_police': 6, 'find_restaurant': 7, 'find_taxi': 8, 'find_train': 9}
20it [00:08,  2.34it/s]
Traceback (most recent call last):
  File "train_args.py", line 184, in <module>
    train_func(args)
  File "train_args.py", line 65, in train_func
    slot_loss.backward()
  File "/usr/local/lib/python3.7/dist-packages/torch/_tensor.py", line 255, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/__init__.py", line 149, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
KeyboardInterrupt


# Hyperparameters Tunning

In [ ]:
import random

results = []
for _ in range(10):
    ne = 7
    bs = random.choice([16])
    wed = random.choice([100])
    ehd = random.choice([192, 256])
    lr = random.uniform(1e-4, 1e-2)

    print(bs, wed, ehd)

    !cd drive/MyDrive/Development/ID_in_CRS/Bi-Model-Intent-And-Slot && python train_args.py -te {ne} -bb {bs} -es {wed} -lhs {ehd}

    print("#" * 30)

# Fasttext

In [ ]:
!pip install fasttext > /dev/null

In [ ]:
import json
import fasttext
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix

In [ ]:
data_path = "drive/MyDrive/Datasets/MultiWOZ_2.2"

In [ ]:
with open(f"{data_path}/train.json", "r") as json_file:
    train_data = json.load(json_file)
with open(f"{data_path}/validation.json", "r") as json_file:
    val_data = json.load(json_file)
with open(f"{data_path}/test.json", "r") as json_file:
    test_data = json.load(json_file)

In [ ]:
intent_label = "intents"

def read_data(data):
    X, y = [], []

    for id, dlg in data.items():
        for trn in dlg:
            if len(trn[intent_label]) == 1 and trn["speaker"] == 0:
                X.append(" ".join(trn["words"]))
                y.append(trn[intent_label][0])

    return X, y

X_train, y_train = read_data(train_data)
X_val, y_val = read_data(val_data)
X_test, y_test = read_data(test_data)

In [ ]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_val = encoder.transform(y_val)
y_test = encoder.transform(y_test)

{class_name: idx for idx, class_name in enumerate(encoder.classes_)}

{'book_hotel': 0,
 'book_restaurant': 1,
 'book_train': 2,
 'find_attraction': 3,
 'find_hospital': 4,
 'find_hotel': 5,
 'find_police': 6,
 'find_restaurant': 7,
 'find_taxi': 8,
 'find_train': 9}

In [ ]:
def prepare_fasttext_file(filename, X, Y):
    with open(f"{filename}.txt", "w") as txt_file:
        for x, y in zip(X, Y):
            txt_file.write(f"__label__{y} {x}\n")

prepare_fasttext_file("train", X_train, y_train)
prepare_fasttext_file("val", X_val, y_val)
prepare_fasttext_file("test", X_test, y_test)

In [ ]:
import gc

del train_data, X_train, y_train
del val_data, X_val, y_val
del test_data

gc.collect()

152

In [ ]:
model = fasttext.train_supervised(
    input="train.txt",
    autotuneValidationFile="val.txt",
    epoch=3
)

In [ ]:
preds, _ = model.predict(X_test)
preds = [int(pred_label[0][-1]) for pred_label in preds]
print(classification_report(y_test, preds, digits=4))
print(confusion_matrix(y_test, preds))

              precision    recall  f1-score   support

           0     0.7339    0.7507    0.7422       349
           1     0.8045    0.7329    0.7670       292
           2     0.8525    0.7283    0.7855       357
           3     0.8576    0.8764    0.8669       955
           4     0.0000    0.0000    0.0000         0
           5     0.8415    0.8527    0.8471       903
           6     0.5000    0.5000    0.5000         2
           7     0.8118    0.8000    0.8059       825
           8     0.9368    0.8464    0.8893       280
           9     0.9072    0.9537    0.9298      1230

    accuracy                         0.8500      5193
   macro avg     0.7246    0.7041    0.7134      5193
weighted avg     0.8518    0.8500    0.8501      5193

[[ 262   11   13    4    0   43    0   10    0    6]
 [  20  214   10    5    0    6    0   29    2    6]
 [  11   10  260    1    0    3    0    2    2   68]
 [   7    6    2  837    7   25    1   61    6    3]
 [   0    0    0    0    0   

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
